### ISSUE TITLE
Errors on Startup: Un-handled exception from mopiqttfrontend

### ISSUE THREAD

**Issue by NeurosProjekte** [fmarzocca/Mopiqtt#5]
Hey,
i got errors on startup after installing mopiqtt.
It looks like it had problems since a newer mopidy version.

Here some info from the mopidy.log
`Exception ignored in: <function Client.__del__ at 0x1496dafe2b80>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/paho/mqtt/client.py", line 874, in __del__
    self._reset_sockets()
  File "/usr/local/lib/python3.9/dist-packages/paho/mqtt/client.py", line 1133, in _reset_sockets
    self._sock_close()
  File "/usr/local/lib/python3.9/dist-packages/paho/mqtt/client.py", line 1119, in _sock_close
    if not self._sock:
AttributeError: 'Client' object has no attribute '_sock'
ERROR    2024-02-29 21:14:37,328 [7:MainThread] mopidy.commands
  Got un-handled exception from MopiqttFrontend
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mopidy/commands.py", line 248, in _actor_error_handling
    yield
  File "/usr/lib/python3/dist-packages/mopidy/commands.py", line 445, in start_frontends
    frontend_class.start(config=config, core=core)
  File "/usr/lib/python3/dist-packages/pykka/_actor.py", line 91, in start
    obj = cls(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/mopiqtt/frontend.py", line 28, in __init__
    self.mqtt = Comms(frontend=self, **config['mopiqtt'])
  File "/usr/local/lib/python3.9/dist-packages/mopiqtt/mqtt.py", line 28, in __init__
    self.client = mqtt.Client(
TypeError: __init__() missing 1 required positional argument: 'callback_api_version'`

Hope there is any solution for this problem, loved using your mqtt extension in combination with my smarthome :-)
Mopidy runs in docker here, that was no problem in the past.

Regards,
Neuro

**Comment by fmarzocca** [comment]
Which mopidy version are you using? Latest is 3.4.2 and this extension is tested and working with it.

**Comment by fmarzocca** [comment]
Which version of module `paho-mqtt` are you running? There is a breaking change in latest v.2.0 (released few days ago).
Use v. 1.6.x until a new `mopiqtt` release

**Comment by NeurosProjekte** [comment]
Okay, I used the latest version of paho-mqtt. Installed the 1.6.1 now and everything is working fine again :-) 
Thanks for your help, had to remember that for future updates on my docker.

**Comment by fmarzocca** [comment]
Fixed in new release v.1.1.0
